"""Add trial fields to users

Revision ID: 9ba7f675a412
Revises: bcb55d750510
Create Date: 2026-01-16 21:45:44.885421

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ba7f675a412"
down_revision: str | Sequence[str] | None = "bcb55d750510"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("has_used_trial", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column("users", sa.Column("trial_ends_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "trial_ends_at")
    op.drop_column("users", "has_used_trial")
    # ### end Alembic commands ###
