"""add_oauth_accounts

Revision ID: c12c0d05df55
Revises: c7bacc87916a
Create Date: 2026-01-05 13:23:04.093115

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c12c0d05df55"
down_revision: str | Sequence[str] | None = "c7bacc87916a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_oauth_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.Enum("GOOGLE", "GITHUB", name="oauthprovider"), nullable=False),
        sa.Column("provider_user_id", sa.String(length=255), nullable=False),
        sa.Column("provider_email", sa.String(length=255), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=True),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_user_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_user_id", name="uq_oauth_provider_user"),
    )
    op.create_index(
        "ix_oauth_accounts_user_provider",
        "user_oauth_accounts",
        ["user_id", "provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_oauth_accounts_user_id"), "user_oauth_accounts", ["user_id"], unique=False
    )
    # Make hashed_password nullable for OAuth-only users (who have no password)
    op.alter_column("users", "hashed_password", existing_type=sa.VARCHAR(length=255), nullable=True)
    # Note: Removed auto-generated subscription_status change - it was an unintended side effect
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore hashed_password as non-nullable (existing users must have passwords again)
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_index(op.f("ix_user_oauth_accounts_user_id"), table_name="user_oauth_accounts")
    op.drop_index("ix_oauth_accounts_user_provider", table_name="user_oauth_accounts")
    op.drop_table("user_oauth_accounts")
    # ### end Alembic commands ###
