app = 'ace-platform-web-staging'
primary_region = 'iad'

[build]
  dockerfile = "Dockerfile"
  [build.args]
    VITE_API_URL = "https://ace-platform-staging.fly.dev"
    VITE_DOCS_URL = "https://ace-platform-docs-staging.fly.dev"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
